### parameter draw ###

# Last updated: 16th October 2020

# This R script draws a set of parameter vectors to be used (one at a time) by the 
# agent fill module.

# install.packages("lhs")

# Switch on necessary packages
library("lhs")

# Set work environment
work <- "desktop" # Choice between 'desktop' and 'laptop'. Ensures script uses correct directories.

# Set number of vector draws needed. NB: minimum should be 10 times the number of parameters in emulator i.e. 10 x m/2)
n <- 450

# Set number of parameters included in the draw (NB: this is the same as the number of parameters for the model run
# but remember that you need both male and female parameters)
m <- 40

# Generate latin hypercube sample
X <- randomLHS(n, m)

# Build the input data file. This bit draws from up to six sources, depending on the model run:
# 1. The csv file that is generated by risk factors.R
# 2. Results from analysis of Smolina et al. to generate the constant incidence (depending on model run), case fatality,
#    and survival rates for MI
# 3. A csv file generated from demo.R that describes mortality rates over time from other causes
# 4. Two arbitrarily assigned treatment parameters, representing percentage decline in incidence and case fataity
#    per year
# 5. Results from a lit review of relative risks, drawn from Excel-based analyses stored in the Relative risks data
#    repository, and that control trends in risk factors

# Set directory where all the inputs are found
if (work=="desktop") { # This sets the directory according to the initial settings
  setwd("K:\\CPNP\\Pete\\MODELLING ALL RISK FACTORS\\microPRIME\\Data repositories\\Parameter space")
} else {
  if (work=="laptop"){
    setwd("F:\\microPRIME\\Data repositories\\Parameter space")
  }  else { "Error" }
}

# Open csv from risk factors.R, if including population-level parameters
# parameters1 <- read.csv("Parameter space_31OCT2017.csv") 

# Open csv from Smolina et al. analysis
parameters2 <- read.csv("Lowest level MI risk_08SEP2020.csv")

# Open csv from demo.R, if including other mortality risk parameters
# parameters3 <- read.csv("Other mortality parameters_10NOV2017.csv")

# Generate treatment parameters
inc.decline.m <- 0.02 # i.e. a 2% decline per year due to improvements in healthcare related prevention
cf.decline.m  <- 0.05 # i.e. a 5% decline per year due to improvements in treatment post MI
inc.decline.f <- 0.02 # i.e. a 2% decline per year due to improvements in healthcare related prevention
cf.decline.f  <- 0.05 # i.e. a 5% decline per year due to improvements in treatment post MI

treatment.inc.mi.m <- c(inc.decline.m*0.7, inc.decline.m*1.3, 
                      NA, NA, NA, NA, NA, NA, NA, NA, "arbitrary")
treatment.cf.mi.m  <- c(cf.decline.m*0.7,  cf.decline.m*1.3, 
                      NA, NA, NA, NA, NA, NA, NA, NA, "arbitrary")
treatment.inc.mi.f <- c(inc.decline.f*0.7, inc.decline.f*1.3, 
                        NA, NA, NA, NA, NA, NA, NA, NA, "arbitrary")
treatment.cf.mi.f  <- c(cf.decline.f*0.7,  cf.decline.f*1.3, 
                        NA, NA, NA, NA, NA, NA, NA, NA, "arbitrary")

# Combine into single dataset
parameters4 <- rbind(treatment.inc.mi.m,
                     treatment.cf.mi.m,
                     treatment.inc.mi.f,
                     treatment.cf.mi.f)

varnames <- c("range1lo",
              "range1hi",
              "range2lo",
              "range2hi",
              "range3lo",
              "range3hi",
              "range4lo",
              "range4hi",
              "range5lo",
              "range5hi",
              "type")
colnames(parameters4) <- varnames

if (work=="desktop") { # This sets the directory according to the initial settings
  setwd("K:\\CPNP\\Pete\\MODELLING ALL RISK FACTORS\\microPRIME\\Data repositories\\Parameter space")
} else {
  if (work=="laptop"){
    setwd("F:\\microPRIME\\Data repositories\\Parameter space")
  }  else { "Error" }
}

write.csv(parameters4, "Treatment parameters_27JUN2019.csv")
parameters4 <- read.csv("Treatment parameters_27JUN2019.csv")

# Open csv from Relative risks data repository
parameters5 <- read.csv("Relative risks_08SEP2020_worst.csv")

# Combine datasets
parameters_all <- rbind(#parameters1,
                        parameters2,
                        #parameters3,
                        parameters4,
                        parameters5)

# Export parameters_all for use in emulator
write.csv(parameters_all[,1:3],"parameters_all_08SEP2020_worst.csv")

# Name variables
colnames <- c(#"bmi.pos.m",
              #"bmi.shp.m",
              #"bmi.pos.f",
              #"bmi.shp.f",
              #"sbp.pos.m",
              #"sbp.shp.m",
              #"sbp.pos.f",
              #"sbp.shp.f",
              #"tcho.pos.m",
              #"tcho.shp.m",
              #"tcho.pos.f",
              #"tcho.shp.f",
              #"smok.prev.m",
              #"smok.prev.f",
              #"diab.prev.m",
              #"diab.prev.f",
              #"age.bmi.mr.m",
              #"age.sbp.mr.m",
              #"age.tcho.mr.m",
              #"age.smok.mr.m",
              #"age.diab.mr.m",
              #"bmi.sbp.mr.m",
              #"bmi.tcho.mr.m",
              #"bmi.smok.mr.m",
              #"bmi.diab.mr.m",
              #"sbp.tcho.mr.m",
              #"sbp.smok.mr.m",
              #"sbp.diab.mr.m",
              #"tcho.smok.mr.m",
              #"tcho.diab.mr.m",
              #"smok.diab.mr.m",
              #"age.bmi.mr.f",
              #"age.sbp.mr.f",
              #"age.tcho.mr.f",
              #"age.smok.mr.f",
              #"age.diab.mr.f",
              #"bmi.sbp.mr.f",
              #"bmi.tcho.mr.f",
              #"bmi.smok.mr.f",
              #"bmi.diab.mr.f",
              #"sbp.tcho.mr.f",
              #"sbp.smok.mr.f",
              #"sbp.diab.mr.f",
              #"tcho.smok.mr.f",
              #"tcho.diab.mr.f",
              #"smok.diab.mr.f",
              "alpha.30dcf.m",
              "alpha.30dcf.f",
              #"beta1.surv.m",
              #"beta1.surv.f",
              #"alpha.mort.m",
              #"alpha.mort.f",
              "treatment.inc.mi.m",
              "treatment.cf.mi.m",
              "treatment.inc.mi.f",
              "treatment.cf.mi.f",
              "bmi.m.r1525",
              "bmi.m.r2550",
              "bmi.f.r1525",
              "bmi.f.r2550",
              "sbp.alpha.m",
              "sbp.alpha.f",
              "tcho.alpha.m",
              "tcho.alpha.f",
              "smok.alpha.m",
              "smok.alpha.f",
              "diab.m",
              "diab.f",
              "bmi.meannl.age.m",
              "bmi.meannl.year.m",
              #"bmi.sdtrend.age.m",
              #"bmi.sdtrend.year.m",
              "bmi.meannl.age.f",
              "bmi.meannl.year.f",
              #"bmi.sdtrend.age.f",
              #"bmi.sdtrend.year.f",
              "sbp.trend.age.m",
              "sbp.trend.age.f",
              "sbp.trend.year.m",
              "sbp.trend.year.f",
              "tcho.trend.age.m",
              "tcho.trend.age.f",
              "tcho.trend.year.m",
              "tcho.trend.year.f",
              "smok.trend.age.m",
              "smok.trend.age.f",
              "smok.trend.year.m",
              "smok.trend.year.f",
              "diab.trend.age.m",
              "diab.trend.age.f",
              "diab.trend.year.m",
              "diab.trend.year.f",
              "prev.alpha.m",
              "prev.alpha.f")
colnames(X) <- colnames

## Translate the [0,1] range in X to the ranges shown in Parameter Space

p           <- parameters_all                            # NB: change to correct input file.
colnames.p  <- c("parameter", letters[1:10], "type")     # This labels each column with letters
colnames(p) <- colnames.p                                # which is needed for the horrible functions
                                                         # below.

# Develop function to get from [0,1] to plausible parameter space
mytranslate1 <- function(z, y) {
    p$a[y]+z*(p$b[y]-p$a[y])
    }
mytranslate2 <- function(z, y) {
  if(z<((p$b[y]-p$a[y])/(p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
    p$a[y]+z*(p$d[y]-p$c[y]+p$b[y]-p$a[y])
  } else {
    p$a[y]+z*(p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y] 
  }
}
mytranslate3 <- function(z, y) {
  if(z<((p$b[y]-p$a[y])/(p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
    p$a[y]+z*(p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])
  } else {
    if(z<((p$d[y]-p$c[y]+p$b[y]-p$a[y])/(p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
      p$a[y]+z*(p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]
    } else {
      p$a[y]+z*(p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]+p$e[y]-p$d[y]
    }
  }
}
mytranslate4 <- function(z,y) {
  if(z<((p$b[y]-p$a[y])/(p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
    p$a[y]+z*(p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])
  } else {
    if(z<((p$d[y]-p$c[y]+p$b[y]-p$a[y])/(p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
      p$a[y]+z*(p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]
    } else {
      if(z<((p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])/(p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
        p$a[y]+z*(p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]+p$e[y]-p$d[y]
      } else {
        p$a[y]+z*(p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]+p$e[y]-p$d[y]+p$g[y]-p$f[y]
      }
    }
  }
}
mytranslate5 <- function(z,y) {
  if(z<((p$b[y]-p$a[y])/(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
    p$a[y]+z*(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])
  } else {
    if(z<((p$d[y]-p$c[y]+p$b[y]-p$a[y])/(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
      p$a[y]+z*(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]
    } else {
      if(z<((p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])/(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
        p$a[y]+z*(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]+p$e[y]-p$d[y]
      } else {
        if(z<((p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])/(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y]))){
          p$a[y]+z*(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]+p$e[y]-p$d[y]+p$g[y]-p$f[y]
        } else {
          p$a[y]+z*(p$j[y]-p$i[y]+p$h[y]-p$g[y]+p$f[y]-p$e[y]+p$d[y]-p$c[y]+p$b[y]-p$a[y])+p$c[y]-p$b[y]+p$e[y]-p$d[y]+p$g[y]-p$f[y]+p$i[y]-p$h[y]
        }
      }
    }
  }
}

# Set up empty parameters, which will be appended to for the translation dataset
for (i in 1:m) {
  assign(paste0("par",i), c())
  }

# Loop round the parameters in the Parameter Space dataset
for (k in (1:m)){
  if(is.na(p$c[k])){
    for (q in (1:n)){
      assign(paste0("par",k), append(get(paste0("par",k)), mytranslate1(X[q,k],k)))
      }
  } else {
    if(is.na(p$e[k])){
      for (q in (1:n)){
        assign(paste0("par",k), append(get(paste0("par",k)), mytranslate2(X[q,k],k)))
      }
    } else {
      if(is.na(p$g[k])){
        for (q in (1:n)){
          assign(paste0("par",k), append(get(paste0("par",k)), mytranslate3(X[q,k],k)))
        }
      } else {
        if(is.na(p$i[k])){
          for (q in (1:n)){
            assign(paste0("par",k), append(get(paste0("par",k)), mytranslate4(X[q,k],k)))
          }
        } else{
          for (q in (1:n)){
            assign(paste0("par",k), append(get(paste0("par",k)), mytranslate5(X[q,k],k)))
          }
        }
      }
    }
  }
  
}

# Strip off the names
for (i in 1:m){
  assign(paste0("par",i),unname(get(paste0("par",i))))
}

# Combine back into dataframe
vector.sample <- do.call(cbind,lapply(paste0("par", 1:m), get))
colnames(vector.sample) <- colnames

# Export to a csv
if (work=="desktop") { # This sets the directory according to the initial settings
  setwd("K:\\CPNP\\Pete\\MODELLING ALL RISK FACTORS\\microPRIME\\Data repositories\\Random draws")
} else {
  if (work=="laptop"){
    setwd("F:\\microPRIME\\Data repositories\\Random draws")
  }  else { "Error" }
}

write.csv(vector.sample, file = "Random draws_08SEP2020_worst.csv") # NB: Update to correct file name.

