### training data set up ###

# Last updated: 22nd April 2021

# This R script is used to set up the training data inputs to be used in emulator.R

work <- "desktop"

n <- 450 # This is the number of iterations which have been run

# Open input data
if (work=="desktop") { # This sets the directory according to the initial settings
  setwd("K:\\CPNP\\Pete\\MODELLING ALL RISK FACTORS\\microPRIME\\Data repositories\\Random Draws")
} else {
  if (work=="laptop"){
    setwd("F:\\microPRIME\\Data repositories\\Random Draws")
  }  else { "Error" }
}
train.input <- read.csv("Random draws_12APR2021.csv") # Update this with the input from the previous microsim run.

# Open the outcomes that were generated by the microsim script
if (work=="desktop") { # This sets the directory according to the initial settings
  setwd("K:\\CPNP\\Pete\\MODELLING ALL RISK FACTORS\\microPRIME\\Data repositories\\Training data")
} else {
  if (work=="laptop"){
    setwd("F:\\microPRIME\\Data repositories\\Training data")
  }  else { "Error" }
}
train.output <- read.csv("Model 18 Wave 2 WORST_17APR2021.csv")

# Name the variables in train.output
# Rename variables - NB: the following script is taken from microsim diagnostics.R
names(train.output)[1] <- "iteration"

incyears  <- c(1999, 2003, 2007, 2011, 2018)        # Years output data were collected from
prevyears <- c(1999, 2003, 2005, 2006, 2011, 2018)  # These should be the same as in the microsim script
eveyears  <- c(1999, 2003, 2007, 2011, 2018)

for (j in 1:length(incyears)) {
  for (i in 1:4) {
    names(train.output)[(j-1)*8+(i-1)*2+2] <- paste0("incrate.m.",incyears[j],".",i)
    # NB: (j-1)*8, because there are eight variables for every year (4 age groups, rate and variance for each)
    # (i-1)*2, because there are two variables for every age group
    # +2, because we need to start with variable 2 (since variable 1 is "iteration")
    names(train.output)[(j-1)*8+(i-1)*2+3] <- paste0("var.inc.m.",incyears[j],".",i)
  }
}

for (j in 1:length(incyears)) {
  for (i in 1:4) {
    names(train.output)[(j-1)*8+(i-1)*2+2+length(incyears)*8] <- paste0("incrate.f.",incyears[j],".",i)
    names(train.output)[(j-1)*8+(i-1)*2+3+length(incyears)*8] <- paste0("var.inc.f.",incyears[j],".",i)
  }
}

for (j in 1:length(prevyears)) {
  for (i in 1:4) {
    names(train.output)[(j-1)*8+(i-1)*2+2+length(incyears)*8*2] <- paste0("prevrate.m.",prevyears[j],".",i)
    names(train.output)[(j-1)*8+(i-1)*2+3+length(incyears)*8*2] <- paste0("var.prev.m.",prevyears[j],".",i)
  }
}

for (j in 1:length(prevyears)) {
  for (i in 1:4) {
    names(train.output)[(j-1)*8+(i-1)*2+2+length(incyears)*8*2+length(prevyears)*8] <- paste0("prevrate.f.",prevyears[j],".",i)
    names(train.output)[(j-1)*8+(i-1)*2+3+length(incyears)*8*2+length(prevyears)*8] <- paste0("var.prev.f.",prevyears[j],".",i)
  }
}

for (j in 1:length(eveyears)) {
  for (i in 1:4) {
    names(train.output)[(j-1)*8+(i-1)*2+2+length(incyears)*8*2+length(prevyears)*8*2] <- paste0("everate.m.",eveyears[j],".",i)
    names(train.output)[(j-1)*8+(i-1)*2+3+length(incyears)*8*2+length(prevyears)*8*2] <- paste0("var.eve.m.",eveyears[j],".",i)
  }
}

for (j in 1:length(eveyears)) {
  for (i in 1:4) {
    names(train.output)[(j-1)*8+(i-1)*2+2+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8] <- paste0("everate.f.",eveyears[j],".",i)
    names(train.output)[(j-1)*8+(i-1)*2+3+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8] <- paste0("var.eve.f.",eveyears[j],".",i)
  }
}

# Restrict to years where external dataset has estimates
inc.ext  <- c(2007)
prev.ext <- c(2003, 2005, 2006, 2011)
eve.ext  <- c(1999, 2003, 2007)

# Functions for age-standardising rates and variance
esp <- function(a,b,c,d) {
  (a*13/100)+(b*7/100)+(c*3/100)+(d*1/100)
}

varesp <- function(a,b,c,d) {
  ((a*13)+(b*7)+(c*3)+(d*1))/sum(13,7,3,1)
}

# Create vectors that map the external dataset years to the collected data
inc.map <- 1:length(incyears)
for (i in inc.map) {                                    # This returns a vector, length of incyears, with zeroes where
  if (incyears[i]%in%inc.ext==TRUE) { inc.map[i] <- i } # the year isn't in the external dataset, and vector position
  else { inc.map[i] <- 0 }                              # where it is
}
prev.map <- 1:length(prevyears)
for (i in prev.map) {
  if (prevyears[i]%in%prev.ext==TRUE) { prev.map[i] <- i }
  else { prev.map[i] <- 0 }
}
eve.map <- 1:length(eveyears)
for (i in eve.map) {
  if (eveyears[i]%in%eve.ext==TRUE) { eve.map[i] <- i }
  else { eve.map[i] <- 0 }
}

# Collect gender-specific outcomes
train.output.m <- NULL
for (i in inc.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- cbind(train.output[,8*(i-1)+2],
                     train.output[,8*(i-1)+4],
                     train.output[,8*(i-1)+6],
                     train.output[,8*(i-1)+8])
    train.output.m <- cbind(train.output.m,collect)
  }
}
for (i in prev.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- cbind(train.output[,8*(i-1)+2+length(incyears)*8*2],
                     train.output[,8*(i-1)+4+length(incyears)*8*2],
                     train.output[,8*(i-1)+6+length(incyears)*8*2],
                     train.output[,8*(i-1)+8+length(incyears)*8*2])
    train.output.m <- cbind(train.output.m,collect)
  }
}
#for (i in eve.map) { # NB: Use this code for checking data extraction is correct.
#  if (i==0) { print("PASS") }
#  else {
#    collect <- cbind(train.output[,8*(i-1)+2+length(incyears)*8*2+length(prevyears)*8*2],
#                     train.output[,8*(i-1)+4+length(incyears)*8*2+length(prevyears)*8*2],
#                     train.output[,8*(i-1)+6+length(incyears)*8*2+length(prevyears)*8*2],
#                     train.output[,8*(i-1)+8+length(incyears)*8*2+length(prevyears)*8*2])
#    train.output.m <- cbind(train.output.m,collect)
#  }
#}

for (i in eve.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- as.numeric(mapply(esp,
                                 train.output[,8*(i-1)+2+length(incyears)*8*2+length(prevyears)*8*2],
                                 train.output[,8*(i-1)+4+length(incyears)*8*2+length(prevyears)*8*2],
                                 train.output[,8*(i-1)+6+length(incyears)*8*2+length(prevyears)*8*2],
                                 train.output[,8*(i-1)+8+length(incyears)*8*2+length(prevyears)*8*2]))
    train.output.m <- cbind(train.output.m,collect)
  }
}

train.var.m <- NULL
for (i in inc.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- cbind(train.output[,8*(i-1)+3],
                     train.output[,8*(i-1)+5],
                     train.output[,8*(i-1)+7],
                     train.output[,8*(i-1)+9])
    train.var.m <- cbind(train.var.m,collect)
  }
}
for (i in prev.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- cbind(train.output[,8*(i-1)+3+length(incyears)*8*2],
                     train.output[,8*(i-1)+5+length(incyears)*8*2],
                     train.output[,8*(i-1)+7+length(incyears)*8*2],
                     train.output[,8*(i-1)+9+length(incyears)*8*2])
    train.var.m <- cbind(train.var.m,collect)
  }
}
#for (i in eve.map) {
#  if (i==0) { print("PASS") }
#  else {
#    collect <- cbind(train.output[,8*(i-1)+3+length(incyears)*8*2+length(prevyears)*8*2],
#                     train.output[,8*(i-1)+5+length(incyears)*8*2+length(prevyears)*8*2],
#                     train.output[,8*(i-1)+7+length(incyears)*8*2+length(prevyears)*8*2],
#                     train.output[,8*(i-1)+9+length(incyears)*8*2+length(prevyears)*8*2])
#    train.var.m <- cbind(train.var.m,collect)
#  }
#}
for (i in eve.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- as.numeric(mapply(varesp,
                                 train.output[,8*(i-1)+3+length(incyears)*8*2+length(prevyears)*8*2],
                                 train.output[,8*(i-1)+5+length(incyears)*8*2+length(prevyears)*8*2],
                                 train.output[,8*(i-1)+7+length(incyears)*8*2+length(prevyears)*8*2],
                                 train.output[,8*(i-1)+9+length(incyears)*8*2+length(prevyears)*8*2]))
    train.var.m <- cbind(train.var.m,collect)
  }
}

# Women
train.output.f <- NULL
for (i in inc.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- cbind(train.output[,8*(i-1)+2+length(incyears)*8],
                     train.output[,8*(i-1)+4+length(incyears)*8],
                     train.output[,8*(i-1)+6+length(incyears)*8],
                     train.output[,8*(i-1)+8+length(incyears)*8])
    train.output.f <- cbind(train.output.f,collect)
  }
}
for (i in prev.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- cbind(train.output[,8*(i-1)+2+length(incyears)*8*2+length(prevyears)*8],
                     train.output[,8*(i-1)+4+length(incyears)*8*2+length(prevyears)*8],
                     train.output[,8*(i-1)+6+length(incyears)*8*2+length(prevyears)*8],
                     train.output[,8*(i-1)+8+length(incyears)*8*2+length(prevyears)*8])
    train.output.f <- cbind(train.output.f,collect)
  }
}
#for (i in eve.map) {
#  if (i==0) { print("PASS") }
#  else {
#    collect <- cbind(train.output[,8*(i-1)+2+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
#                     train.output[,8*(i-1)+4+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
#                     train.output[,8*(i-1)+6+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
#                     train.output[,8*(i-1)+8+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8])
#    train.output.f <- cbind(train.output.f,collect)
#  }
#}
for (i in eve.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- as.numeric(mapply(esp,
                                 train.output[,8*(i-1)+2+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
                                 train.output[,8*(i-1)+4+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
                                 train.output[,8*(i-1)+6+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
                                 train.output[,8*(i-1)+8+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8]))
    train.output.f <- cbind(train.output.f,collect)
  }
}

train.var.f <- NULL
for (i in inc.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- cbind(train.output[,8*(i-1)+3+length(incyears)*8],
                     train.output[,8*(i-1)+5+length(incyears)*8],
                     train.output[,8*(i-1)+7+length(incyears)*8],
                     train.output[,8*(i-1)+9+length(incyears)*8])
    train.var.f <- cbind(train.var.f,collect)
  }
}
for (i in prev.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- cbind(train.output[,8*(i-1)+3+length(incyears)*8*2+length(prevyears)*8],
                     train.output[,8*(i-1)+5+length(incyears)*8*2+length(prevyears)*8],
                     train.output[,8*(i-1)+7+length(incyears)*8*2+length(prevyears)*8],
                     train.output[,8*(i-1)+9+length(incyears)*8*2+length(prevyears)*8])
    train.var.f <- cbind(train.var.f,collect)
  }
}
#for (i in eve.map) {
#  if (i==0) { print("PASS") }
#  else {
#    collect <- cbind(train.output[,8*(i-1)+3+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
#                     train.output[,8*(i-1)+5+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
#                     train.output[,8*(i-1)+7+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
#                     train.output[,8*(i-1)+9+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8])
#    train.var.f <- cbind(train.var.f,collect)
#  }
#}
for (i in eve.map) {
  if (i==0) { print("PASS") }
  else {
    collect <- as.numeric(mapply(varesp,
                                 train.output[,8*(i-1)+3+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
                                 train.output[,8*(i-1)+5+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
                                 train.output[,8*(i-1)+7+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8],
                                 train.output[,8*(i-1)+9+length(incyears)*8*2+length(prevyears)*8*2+length(eveyears)*8]))
    train.var.f <- cbind(train.var.f,collect)
  }
}


# Name gender-specific outputs
train.output.m <- as.data.frame(train.output.m)
train.var.m    <- as.data.frame(train.var.m)
train.output.f <- as.data.frame(train.output.f)
train.var.f    <- as.data.frame(train.var.f)
for (j in 1:length(inc.ext)) {
  for (i in 1:4) {
    names(train.output.m)[(j-1)*4+i] <- paste0("incrate.m.",inc.ext[j],".",i)
    names(train.var.m)[(j-1)*4+i] <- paste0("var.inc.m.",inc.ext[j],".",i)
    names(train.output.f)[(j-1)*4+i] <- paste0("incrate.f.",inc.ext[j],".",i)
    names(train.var.f)[(j-1)*4+i] <- paste0("var.inc.f.",inc.ext[j],".",i)
  }
}

for (j in 1:length(prev.ext)) {
  for (i in 1:4) {
    names(train.output.m)[(j-1)*4+i+length(inc.ext)*4] <- paste0("prevrate.m.",prev.ext[j],".",i)
    names(train.var.m)[(j-1)*4+i+length(inc.ext)*4] <- paste0("var.prev.m.",prev.ext[j],".",i)
    names(train.output.f)[(j-1)*4+i+length(inc.ext)*4] <- paste0("prevrate.f.",prev.ext[j],".",i)
    names(train.var.f)[(j-1)*4+i+length(inc.ext)*4] <- paste0("var.prev.f.",prev.ext[j],".",i)
  }
}

#for (j in 1:length(eve.ext)) {
#  for (i in 1:4) {
#    names(train.output.m)[(j-1)*4+i+length(inc.ext)*4+length(prev.ext)*4] <- paste0("everate.m.",eve.ext[j],".",i)
#    names(train.var.m)[(j-1)*4+i+length(inc.ext)*4+length(prev.ext)*4] <- paste0("var.eve.m.",eve.ext[j],".",i)
#    names(train.output.f)[(j-1)*4+i+length(inc.ext)*4+length(prev.ext)*4] <- paste0("everate.f.",eve.ext[j],".",i)
#    names(train.var.f)[(j-1)*4+i+length(inc.ext)*4+length(prev.ext)*4] <- paste0("var.eve.f.",eve.ext[j],".",i)
#  }
#}
for (j in 1:length(eve.ext)) {
    names(train.output.m)[j+length(inc.ext)*4+length(prev.ext)*4] <- paste0("everate.m.",eve.ext[j],".all")
    names(train.var.m)[j+length(inc.ext)*4+length(prev.ext)*4] <- paste0("var.eve.m.",eve.ext[j],".all")
    names(train.output.f)[j+length(inc.ext)*4+length(prev.ext)*4] <- paste0("everate.f.",eve.ext[j],".all")
    names(train.var.f)[j+length(inc.ext)*4+length(prev.ext)*4] <- paste0("var.eve.f.",eve.ext[j],".all")
}

# Check with some correlations (should produce perfect correlation)
#cor(train.output$incrate.m.2007.3,train.output.m$incrate.m.2007.3)
#cor(train.output$incrate.f.2007.2,train.output.f$incrate.f.2007.2)
#cor(train.output$var.inc.m.2007.1,train.var.m$var.inc.m.2007.1)
#cor(train.output$var.inc.f.2007.4,train.var.f$var.inc.f.2007.4)
#cor(train.output$prevrate.m.2005.3,train.output.m$prevrate.m.2005.3)
#cor(train.output$prevrate.f.2005.2,train.output.f$prevrate.f.2005.2)
#cor(train.output$var.prev.m.2005.1,train.var.m$var.prev.m.2005.1)
#cor(train.output$var.prev.f.2005.4,train.var.f$var.prev.f.2005.4)
#cor(train.output$everate.m.2007.3,train.output.m$everate.m.2007.3)
#cor(train.output$everate.f.2007.2,train.output.f$everate.f.2007.2)
#cor(train.output$var.eve.m.2007.1,train.var.m$var.eve.m.2007.1)
#cor(train.output$var.eve.f.2007.4,train.var.f$var.eve.f.2007.4)


# Generate gender-specific input and output datasets
train.input.m <- subset(train.input, select = c(#"bmi.pos.m",
                                                #"bmi.shp.m",
                                                #
                                                #
                                                #"sbp.pos.m",
                                                #"sbp.shp.m",
                                                #
                                                #
                                                #"tcho.pos.m",
                                                #"tcho.shp.m",
                                                #
                                                #
                                                #"smok.prev.m",
                                                #
                                                #"diab.prev.m",
                                                #
                                                #"age.bmi.mr.m",
                                                #"age.sbp.mr.m",
                                                #"age.tcho.mr.m",
                                                #"age.smok.mr.m",
                                                #"age.diab.mr.m",
                                                #"bmi.sbp.mr.m",
                                                #"bmi.tcho.mr.m",
                                                #"bmi.smok.mr.m",
                                                #"bmi.diab.mr.m",
                                                #"sbp.tcho.mr.m",
                                                #"sbp.smok.mr.m",
                                                #"sbp.diab.mr.m",
                                                #"tcho.smok.mr.m",
                                                #"tcho.diab.mr.m",
                                                #"smok.diab.mr.m",
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                "alpha.30dcf.m",
                                                #
                                                #"beta1.surv.m",
                                                #
                                                #"alpha.mort.m",
                                                #
                                                #"treatment.inc.mi.m",
                                                "treatment.cf.mi.m",
                                                #
                                                #
                                                "bmi.m.r1525",
                                                "bmi.m.r2550",
                                                #
                                                #
                                                "sbp.alpha.m",
                                                #
                                                "tcho.alpha.m",
                                                #
                                                "smok.alpha.m",
                                                #
                                                "diab.m",
                                                #
                                                "bmi.trend.age.m",
                                                "bmi.trend.year.m",
                                                #"bmi.sdtrend.age.m",
                                                #"bmi.sdtrend.year.m",
                                                #
                                                #
                                                #
                                                #
                                                "sbp.trend.age.m",
                                                #
                                                "sbp.trend.year.m",
                                                #
                                                "tcho.trend.age.m",
                                                #
                                                "tcho.trend.year.m",
                                                #
                                                "smok.trend.age.m",
                                                #
                                                "smok.trend.year.m",
                                                #
                                                "diab.trend.age.m",
                                                #
                                                "diab.trend.year.m",
                                                #
                                                "prev.alpha.m"))

train.input.f <- subset(train.input, select = c(#"bmi.pos.f",
                                                #"bmi.shp.f",
                                                #
                                                #
                                                #"sbp.pos.f",
                                                #"sbp.shp.f",
                                                #
                                                #
                                                #"tcho.pos.f",
                                                #"tcho.shp.f",
                                                #
                                                #"smok.prev.f",
                                                #
                                                #"diab.prev.f",
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #
                                                #"age.bmi.mr.f",
                                                #"age.sbp.mr.f",
                                                #"age.tcho.mr.f",
                                                #"age.smok.mr.f",
                                                #"age.diab.mr.f",
                                                #"bmi.sbp.mr.f",
                                                #"bmi.tcho.mr.f",
                                                #"bmi.smok.mr.f",
                                                #"bmi.diab.mr.f",
                                                #"sbp.tcho.mr.f",
                                                #"sbp.smok.mr.f",
                                                #"sbp.diab.mr.f",
                                                #"tcho.smok.mr.f",
                                                #"tcho.diab.mr.f",
                                                #"smok.diab.mr.f",
                                                #
                                                "alpha.30dcf.f",
                                                #
                                                #"beta1.surv.f",
                                                #
                                                #"alpha.mort.f",
                                                #
                                                #
                                                #"treatment.inc.mi.f",
                                                "treatment.cf.mi.f",
                                                #
                                                #
                                                "bmi.f.r1525",
                                                "bmi.f.r2550",
                                                #
                                                "sbp.alpha.f",
                                                #
                                                "tcho.alpha.f",
                                                #
                                                "smok.alpha.f",
                                                #
                                                "diab.f",
                                                #
                                                #
                                                #
                                                #
                                                "bmi.trend.age.f",
                                                "bmi.trend.year.f",
                                                #"bmi.sdtrend.age.f",
                                                #"bmi.sdtrend.year.f",
                                                #
                                                "sbp.trend.age.f",
                                                #
                                                "sbp.trend.year.f",
                                                #
                                                "tcho.trend.age.f",
                                                #
                                                "tcho.trend.year.f",
                                                #
                                                "smok.trend.age.f",
                                                #
                                                "smok.trend.year.f",
                                                #
                                                "diab.trend.age.f",
                                                #
                                                "diab.trend.year.f",
                                                #
                                                "prev.alpha.f"))

# Restrict to the random draws used in the model run
train.input.m <- train.input.m[1:n,]
train.input.f <- train.input.f[1:n,]

# Export and save as csv
if (work=="desktop") { # This sets the directory according to the initial settings
  setwd("K:\\CPNP\\Pete\\MODELLING ALL RISK FACTORS\\microPRIME\\Data repositories\\Training data")
} else {
  if (work=="laptop"){
    setwd("F:\\microPRIME\\Data repositories\\Training data")
  }  else { "Error" }
}

write.csv(train.input.m,  file = "train.input.m_17APR2021.csv") 
write.csv(train.input.f,  file = "train.input.f_17APR2021.csv") 
write.csv(train.output.m, file = "train.output.m_17APR2021.csv") # NB: You must go and manually erase 55-64 in 2005
write.csv(train.output.f, file = "train.output.f_17APR2021.csv") # NB: You must go and manually erase 55-64 in 2005
write.csv(train.var.m,    file = "train.output.var.m_17APR2021.csv") # NB: You must go and manually erase 55-64 in 2005
write.csv(train.var.f,    file = "train.output.var.f_17APR2021.csv") # NB: You must go and manually erase 55-64 in 2005
